from typing import Any

from .azure_blob import AzureBlobLoader
from .base import Document
from .bigquery import BigQueryLoader
from .hubspot import HubSpotLoader
from .markdown import MarkdownLoader
from .mesh import GitRepoLoader, LocalMdLoader, MeshPrivacyFilter
from .mongodb import MongoDBLoader
from .onedrive import OneDriveLoader
from .s3 import S3Loader
from .salesforce import SalesforceLoader
from .text import StringLoader, TextLoader
from .visual import (
    DefaultPageRenderer,
    ImagePageRenderer,
    PageRenderer,
    PDFPageRenderer,
    PowerPointPageRenderer,
    VisualPage,
    VisualPageRenderer,
)

__all__ = [
    "AirtableLoader",
    "ArXivLoader",
    "AsanaLoader",
    "AudioLoader",
    "AzureBlobLoader",
    "BigQueryLoader",
    "BoxLoader",
    "ClickUpLoader",
    "CSVLoader",
    "ConfigLoader",
    "ConfluenceLoader",
    "DatabricksLoader",
    "DeltaLoader",
    "DeltaLakeLoader",
    "DirectoryLoader",
    "DiscordLoader",
    "DocxLoader",
    "Document",
    "DynamoDBLoader",
    "DropboxLoader",
    "EPUBLoader",
    "ElasticsearchLoader",
    "EmailLoader",
    "FirestoreLoader",
    "FreshdeskLoader",
    "GCSLoader",
    "GitHubLoader",
    "GitLoader",
    "GitRepoLoader",
    "GmailLoader",
    "GoogleCalendarLoader",
    "GoogleDriveLoader",
    "GoogleSheetsLoader",
    "HackerNewsLoader",
    "HTMLLoader",
    "HubSpotLoader",
    "IcebergLoader",
    "IntercomLoader",
    "KafkaLoader",
    "LaTeXLoader",
    "JSONLoader",
    "JiraLoader",
    "LinearLoader",
    "LocalMdLoader",
    "MarkdownLoader",
    "MondayLoader",
    "MeshPrivacyFilter",
    "MongoDBLoader",
    "NotionLoader",
    "OKFLoader",
    "ObsidianLoader",
    "OneDriveLoader",
    "OpenKnowledgeFormatLoader",
    "PDFLoader",
    "ParquetLoader",
    "PubMedLoader",
    "RSSLoader",
    "RTFLoader",
    "RedditLoader",
    "RedisLoader",
    "S3Loader",
    "SalesforceLoader",
    "ShopifyLoader",
    "SitemapLoader",
    "SnowflakeLoader",
    "SQLLoader",
    "SlackLoader",
    "StringLoader",
    "SupabaseLoader",
    "TeamsLoader",
    "TextLoader",
    "TrelloLoader",
    "TSVLoader",
    "TwitterLoader",
    "VideoLoader",
    "VisualPage",
    "PageRenderer",
    "DefaultPageRenderer",
    "ImagePageRenderer",
    "PDFPageRenderer",
    "PowerPointPageRenderer",
    "VisualPageRenderer",
    "WebLoader",
    "WikipediaLoader",
    "FigmaLoader",
    "GraphQLLoader",
    "ZoomLoader",
    "XMLLoader",
    "YAMLLoader",
    "YouTubeLoader",
    "ZendeskLoader",
    "VisionPDFLoader",
]

_LOADERS = {
    "AirtableLoader": ".airtable",
    "ArXivLoader": ".arxiv",
    "AsanaLoader": ".asana",
    "AzureBlobLoader": ".azure_blob",
    "BigQueryLoader": ".bigquery",
    "BoxLoader": ".box",
    "ClickUpLoader": ".clickup",
    "DatabricksLoader": ".databricks",
    "DeltaLoader": ".delta",
    "DeltaLakeLoader": ".delta",
    "PDFLoader": ".pdf",
    "HTMLLoader": ".html",
    "LaTeXLoader": ".latex",
    "CSVLoader": ".csv",
    "TSVLoader": ".tsv",
    "ConfigLoader": ".config",
    "JSONLoader": ".json_loader",
    "DirectoryLoader": ".directory",
    "WebLoader": ".web",
    "DocxLoader": ".docx",
    "AudioLoader": ".audio",
    "VideoLoader": ".video",
    "VisualPage": ".visual",
    "PageRenderer": ".visual",
    "DefaultPageRenderer": ".visual",
    "ImagePageRenderer": ".visual",
    "PDFPageRenderer": ".visual",
    "PowerPointPageRenderer": ".visual",
    "VisualPageRenderer": ".visual",
    "XMLLoader": ".xml_loader",
    "YAMLLoader": ".yaml_loader",
    "DiscordLoader": ".discord",
    "EmailLoader": ".email",
    "GCSLoader": ".gcs",
    "GitHubLoader": ".github",
    "GitLoader": ".git",
    "GitRepoLoader": ".mesh",
    "GmailLoader": ".gmail",
    "GoogleDriveLoader": ".google_drive",
    "GoogleSheetsLoader": ".google_sheets",
    "HubSpotLoader": ".hubspot",
    "IcebergLoader": ".iceberg",
    "JiraLoader": ".jira",
    "KafkaLoader": ".kafka",
    "LinearLoader": ".linear",
    "SlackLoader": ".slack",
    "NotionLoader": ".notion",
    "OKFLoader": ".okf",
    "OpenKnowledgeFormatLoader": ".okf",
    "ObsidianLoader": ".obsidian",
    "OneDriveLoader": ".onedrive",
    "RSSLoader": ".rss",
    "RTFLoader": ".rtf",
    "S3Loader": ".s3",
    "SalesforceLoader": ".salesforce",
    "ShopifyLoader": ".shopify",
    "SQLLoader": ".sql",
    "SnowflakeLoader": ".snowflake",
    "SupabaseLoader": ".supabase",
    "TeamsLoader": ".teams",
    "WikipediaLoader": ".wikipedia",
    "FigmaLoader": ".figma",
    "GraphQLLoader": ".graphql",
    "ZoomLoader": ".zoom",
    "ConfluenceLoader": ".confluence",
    "MongoDBLoader": ".mongodb",
    "DynamoDBLoader": ".dynamodb",
    "DropboxLoader": ".dropbox",
    "EPUBLoader": ".epub",
    "ParquetLoader": ".parquet",
    "PubMedLoader": ".pubmed",
    "RedisLoader": ".redis_loader",
    "ElasticsearchLoader": ".elasticsearch",
    "SitemapLoader": ".sitemap",
    "YouTubeLoader": ".youtube",
    "FirestoreLoader": ".firebase",
    "FreshdeskLoader": ".freshdesk",
    "GoogleCalendarLoader": ".google_calendar",
    "HackerNewsLoader": ".hackernews",
    "IntercomLoader": ".intercom",
    "LocalMdLoader": ".mesh",
    "MondayLoader": ".monday",
    "RedditLoader": ".reddit",
    "MeshPrivacyFilter": ".mesh",
    "TrelloLoader": ".trello",
    "TwitterLoader": ".twitter",
    "ZendeskLoader": ".zendesk",
    "VisionPDFLoader": ".vision_pdf",
}


def __getattr__(name: str) -> Any:
    if name in _LOADERS:
        import importlib

        mod = importlib.import_module(_LOADERS[name], __name__)
        cls = getattr(mod, name)
        globals()[name] = cls
        return cls
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
