from ._cache import AsyncLRUCache
from .base import BaseLLM, LLMConfig
from .cost_quality_router import CostQualityRouter
from .cost_router import QUALITY_TABLE, CostRouter, CostRouterConfig, RouterModelSpec
from .edge import EdgeFallbackBlockedError, EdgeRouteMetadata, EdgeRuntime, FallbackPolicy
from .fallback_chain import FallbackChain, FallbackChainConfig
from .structured import generate_structured

__all__ = [
    "AI21LLM",
    "AlephAlphaLLM",
    "AnthropicLLM",
    "AsyncLRUCache",
    "AzureOpenAILLM",
    "BaseLLM",
    "BaseReasoningProvider",
    "BedrockLLM",
    "CerebrasLLM",
    "CloudflareLLM",
    "CohereLLM",
    "CostQualityRouter",
    "CostRouter",
    "CostRouterConfig",
    "DatabricksLLM",
    "DeepSeekLLM",
    "DeepInfraLLM",
    "DynamoDBCacheBackend",
    "EdgeFallbackBlockedError",
    "EdgeRouteMetadata",
    "EdgeRuntime",
    "ErnieLLM",
    "FallbackChain",
    "FallbackChainConfig",
    "FallbackPolicy",
    "FireworksLLM",
    "GeminiLLM",
    "GPT4AllLLM",
    "GroqLLM",
    "FriendliLLM",
    "HyperbolicLLM",
    "HuggingFaceLLM",
    "LLMConfig",
    "LlamaCppLLM",
    "LMStudioLLM",
    "MemcachedCacheBackend",
    "MinimaxLLM",
    "MLXLLM",
    "MistralLLM",
    "NvidiaNIMLLM",
    "NebiusLLM",
    "MoonshotLLM",
    "NovitaLLM",
    "OllamaLLM",
    "OpenAILLM",
    "OpenRouterLLM",
    "PerplexityLLM",
    "QUALITY_TABLE",
    "ReasoningLLM",
    "ReasoningResponse",
    "ReasoningStreamChunk",
    "ReplicateLLM",
    "RekaLLM",
    "RouterModelSpec",
    "SambaNovaLLM",
    "TogetherLLM",
    "SnowflakeCortexLLM",
    "BasetenLLM",
    "UpstageLLM",
    "WatsonxLLM",
    "ClarifaiLLM",
    "VertexAILLM",
    "VLLMLLM",
    "WriterLLM",
    "XaiLLM",
    "ZhipuLLM",
    "generate_structured",
]

_PROVIDERS = {
    "AI21LLM": ".ai21",
    "AlephAlphaLLM": ".aleph_alpha",
    "MemcachedCacheBackend": "._cache_memcached",
    "OpenAILLM": ".openai",
    "AzureOpenAILLM": ".azure_openai",
    "AnthropicLLM": ".anthropic",
    "OllamaLLM": ".ollama",
    "CohereLLM": ".cohere",
    "MistralLLM": ".mistral",
    "NovitaLLM": ".novita",
    "GeminiLLM": ".gemini",
    "GPT4AllLLM": ".gpt4all",
    "BedrockLLM": ".bedrock",
    "GroqLLM": ".groq",
    "HuggingFaceLLM": ".huggingface",
    "DeepSeekLLM": ".deepseek",
    "OpenRouterLLM": ".openrouter",
    "TogetherLLM": ".together",
    "FireworksLLM": ".fireworks",
    "PerplexityLLM": ".perplexity",
    "SambaNovaLLM": ".sambanova",
    "CerebrasLLM": ".cerebras",
    "LlamaCppLLM": ".llamacpp",
    "LMStudioLLM": ".lmstudio",
    "VertexAILLM": ".vertex_ai",
    "VLLMLLM": ".vllm",
    "MoonshotLLM": ".moonshot",
    "MinimaxLLM": ".minimax",
    "MLXLLM": ".mlx",
    "XaiLLM": ".xai",
    "WriterLLM": ".writer",
    "ZhipuLLM": ".zhipu",
    "CloudflareLLM": ".cloudflare",
    "DatabricksLLM": ".databricks",
    "DeepInfraLLM": ".deepinfra",
    "FriendliLLM": ".friendli",
    "HyperbolicLLM": ".hyperbolic",
    "NvidiaNIMLLM": ".nvidia_nim",
    "NebiusLLM": ".nebius",
    "RekaLLM": ".reka",
    "SnowflakeCortexLLM": ".snowflake_cortex",
    "BasetenLLM": ".baseten",
    "UpstageLLM": ".upstage",
    "WatsonxLLM": ".watsonx",
    "ClarifaiLLM": ".clarifai",
    "ErnieLLM": ".ernie",
    "DynamoDBCacheBackend": "._cache_dynamodb",
    "BaseReasoningProvider": ".reasoning",
    "ReasoningLLM": ".reasoning",
    "ReasoningResponse": ".reasoning",
    "ReasoningStreamChunk": ".reasoning",
    "ReplicateLLM": ".replicate",
}


def __getattr__(name: str):
    if name in _PROVIDERS:
        import importlib

        mod = importlib.import_module(_PROVIDERS[name], __name__)
        cls = getattr(mod, name)
        globals()[name] = cls
        return cls
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
