"""
SynapseKit — lightweight, async-first RAG framework.

3-line happy path:

    from synapsekit import RAG

    rag = RAG(model="gpt-4o-mini", api_key="sk-...")
    rag.add("Your document text here")

    async for token in rag.stream("What is the main topic?"):
        print(token, end="", flush=True)
"""

from __future__ import annotations

from ._api import deprecated, experimental, public_api
from .a2a import A2AClient, A2AMessage, A2AServer, A2ATask, AgentCard, TaskState
from .agents import (
    ActionEvent,
    AgentBidder,
    AgentClient,
    AgentConfig,
    AgentConfigPatch,
    AgentConfigSnapshot,
    AgentEvolutionAuditLog,
    AgentExecutor,
    AgentFederation,
    AgentMetadata,
    AgentRegistry,
    AgentRoutingStrategy,
    AgentScratchpad,
    AgentStep,
    AgentSwarm,
    AnthropicComputerUseProvider,
    ArxivSearchTool,
    AuctionResult,
    AuctionType,
    BaseTool,
    Bid,
    BidStrategy,
    BingSearchTool,
    BraveSearchTool,
    BrowserScreenProvider,
    BrowserTool,
    CalculatorTool,
    CoalitionFormer,
    CodeInterpreterTool,
    ComputerAction,
    ComputerActionType,
    ComputerObservation,
    ComputerStep,
    ComputerUseAgent,
    ComputerUseProvider,
    ComputerUseResult,
    ContentFilter,
    Crew,
    CrewAgent,
    CrewResult,
    CronTrigger,
    DateTimeTool,
    DuckDuckGoSearchTool,
    EmailTool,
    ErrorEvent,
    EvolutionCycleResult,
    FileListTool,
    FileReadTool,
    FileWriteTool,
    FinalAnswerEvent,
    FunctionCallingAgent,
    GitHubAPITool,
    GoogleSearchTool,
    GraphQLTool,
    GuardrailResult,
    Guardrails,
    Handoff,
    HandoffChain,
    HandoffResult,
    HTTPRequestTool,
    HumanInputTool,
    ImageAnalysisTool,
    ImageGenerationTool,
    InMemoryAgentRegistry,
    JiraTool,
    JSONQueryTool,
    LinearTool,
    LocalAgentClient,
    LocalScreenProvider,
    MarketPolicy,
    MetaAnalyzer,
    NewsTool,
    ObservationEvent,
    OpenAIComputerUseProvider,
    OpenSourceComputerUseProvider,
    PDFReaderTool,
    PIIDetector,
    PIIRedactor,
    PubMedSearchTool,
    PythonREPLTool,
    ReActAgent,
    ReasoningAgent,
    ReasoningAgentConfig,
    ReasoningDecision,
    RedactionResult,
    RedisAgentRegistry,
    RedisReputation,
    RegexTool,
    Reputation,
    ReputationSnapshot,
    RoutingStrategy,
    SafetyPolicy,
    ScreenProvider,
    SelfImprovingAgent,
    SentimentAnalysisTool,
    SessionRecorder,
    ShellTool,
    SimpleAgent,
    SlackTool,
    SpeechToTextTool,
    SQLQueryTool,
    SQLSchemaInspectionTool,
    StepEvent,
    StripeTool,
    SummarizationTool,
    SupervisorAgent,
    SwarmResult,
    Task,
    TavilySearchTool,
    TextToSpeechTool,
    ThoughtEvent,
    TokenEvent,
    ToolRegistry,
    ToolResult,
    TopicRestrictor,
    TranslationTool,
    TriggerResult,
    TwilioTool,
    VectorSearchTool,
    VNCScreenProvider,
    VoiceAgent,
    VoiceResult,
    WeatherTool,
    WebScraperTool,
    WebSearchTool,
    WikipediaTool,
    WolframAlphaTool,
    WorkerAgent,
    YouTubeSearchTool,
    agent,
    requires_human_confirmation,
    tool,
)
from .audit import (
    AuditMetrics,
    AuditRecord,
    AuditSink,
    AuditTracer,
    AuditVerificationError,
    EventKind,
    FileAuditSink,
    MerkleHasher,
    ReplayEngine,
    Signature,
    SigningPolicy,
    Verdict,
    VerifiableAgent,
    VerificationResult,
    export_audit_bundle,
)
from .audit import PIIRedactor as AuditPIIRedactor
from .audit import verify as verify_audit_bundle
from .embeddings.backend import SynapsekitEmbeddings
from .evaluation import (
    EmailAlertSink,
    EvalCaseMeta,
    EvalRegression,
    EvalSnapshot,
    EvalSuite,
    EvalSuiteResult,
    EvaluationPipeline,
    EvaluationResult,
    FaithfulnessMetric,
    GroundednessMetric,
    MetricDelta,
    MetricResult,
    PagerDutyAlertSink,
    PromptCandidate,
    PromptOptimizer,
    PromptVariantRunner,
    RAGAlert,
    RAGAlertSink,
    RAGERemediationSuggestion,
    RAGEvaluationResult,
    RAGEvaluationThresholds,
    RAGEvaluator,
    RegressionReport,
    RelevancyMetric,
    SlackWebhookAlertSink,
    eval_case,
)
from .graph import (
    END,
    BaseCheckpointer,
    CompiledGraph,
    ConditionalEdge,
    ConditionFn,
    Edge,
    EventHooks,
    ExecutionTrace,
    GraphConfigError,
    GraphEvent,
    GraphInterrupt,
    GraphRuntimeError,
    GraphState,
    GraphVisualizer,
    InMemoryCheckpointer,
    InterruptState,
    JSONFileCheckpointer,
    Node,
    NodeFn,
    RecursionDepthError,
    SQLiteCheckpointer,
    StateField,
    StateGraph,
    TraceEntry,
    TypedState,
    agent_node,
    approval_node,
    dynamic_route_node,
    fan_out_node,
    get_mermaid_with_trace,
    llm_node,
    rag_node,
    sse_stream,
    subgraph_node,
    ws_stream,
)
from .hive import (
    HIVE_SCHEMA_VERSION,
    PATTERN_VOCABULARY,
    AllowAllAuthorizer,
    ContributionEnvelope,
    ContributionPayload,
    DifferentialPrivacy,
    HiveAggregator,
    HiveAggregatorError,
    HiveClient,
    HiveClientError,
    HivePrivacyError,
    HiveTransport,
    HttpHiveTransport,
    InProcessHiveTransport,
    MinedPatterns,
    PatternMiner,
    PatternObservation,
    PrivacyBudgetLedger,
    PrivacyConfig,
    Pseudonymizer,
    ShareScope,
    SQLiteHiveStore,
    Suggestion,
    TransparencyReport,
    create_hive_app,
    stable_scope_id,
)
from .llm.base import BaseLLM, LLMConfig
from .llm.cost_quality_router import CostQualityRouter
from .llm.cost_router import QUALITY_TABLE, CostRouter, CostRouterConfig, RouterModelSpec
from .llm.edge import EdgeFallbackBlockedError, EdgeRouteMetadata, EdgeRuntime, FallbackPolicy
from .llm.fallback_chain import FallbackChain, FallbackChainConfig
from .llm.multimodal import AudioContent, ImageContent, MultimodalMessage
from .llm.reasoning import (
    BaseReasoningProvider,
    ReasoningLLM,
    ReasoningResponse,
    ReasoningStreamChunk,
)
from .llm.structured import generate_structured
from .loaders.arxiv import ArXivLoader
from .loaders.azure_blob import AzureBlobLoader
from .loaders.base import Document
from .loaders.bigquery import BigQueryLoader
from .loaders.config import ConfigLoader
from .loaders.confluence import ConfluenceLoader
from .loaders.csv import CSVLoader
from .loaders.directory import DirectoryLoader
from .loaders.dynamodb import DynamoDBLoader
from .loaders.email import EmailLoader
from .loaders.epub import EPUBLoader
from .loaders.gcs import GCSLoader
from .loaders.git import GitLoader
from .loaders.github import GitHubLoader
from .loaders.google_sheets import GoogleSheetsLoader
from .loaders.html import HTMLLoader
from .loaders.hubspot import HubSpotLoader
from .loaders.image import ImageLoader
from .loaders.jira import JiraLoader
from .loaders.json_loader import JSONLoader
from .loaders.latex import LaTeXLoader
from .loaders.markdown import MarkdownLoader
from .loaders.mongodb import MongoDBLoader
from .loaders.obsidian import ObsidianLoader
from .loaders.okf import OKFLoader, OpenKnowledgeFormatLoader
from .loaders.onedrive import OneDriveLoader
from .loaders.pdf import PDFLoader
from .loaders.pubmed import PubMedLoader
from .loaders.rss import RSSLoader
from .loaders.rtf import RTFLoader
from .loaders.s3 import S3Loader
from .loaders.salesforce import SalesforceLoader
from .loaders.snowflake import SnowflakeLoader
from .loaders.sql import SQLLoader
from .loaders.teams import TeamsLoader
from .loaders.text import StringLoader, TextLoader
from .loaders.tsv import TSVLoader
from .loaders.web import WebLoader
from .loaders.wikipedia import WikipediaLoader
from .marketplace import (
    AgentBundleFile,
    AgentBundleVerification,
    AgentManifest,
    AgentMarketplaceError,
    AgentSandbox,
    FileAgentRegistry,
    InstalledAgent,
    InvalidAgentBundleError,
    PublisherIdentity,
    RankedRegistryEntry,
    RegistryEntry,
    SandboxRequiredError,
    SignedAgentReview,
    UntrustedPublisherError,
    install_agent,
    pack_agent,
    unpack_agent,
    verify_agent_bundle,
)
from .mcp import MCPClient, MCPServer, MCPToolAdapter
from .memory import (
    AgentMemory,
    DiffConflictError,
    FileDiffEngine,
    GraphAgentMemory,
    GraphMemoryBackend,
    LivingMemory,
    MemoryFileCategory,
    MemoryFileRouter,
    MemoryPatch,
    MemoryPIIFilter,
    OccurrenceRecord,
    OccurrenceTracker,
    PatchStatus,
    PatchStore,
    PIIFilterResult,
)
from .memory import AgentMemory as PersistentAgentMemory  # deprecated alias, kept 1 release
from .memory.buffer import BufferMemory
from .memory.conversation import ConversationMemory
from .memory.entity import EntityMemory
from .memory.hybrid import HybridMemory
from .memory.redis import RedisConversationMemory
from .memory.smart_context import SmartContextManager
from .memory.sqlite import SQLiteConversationMemory
from .memory.summary_buffer import SummaryBufferMemory
from .memory.token_buffer import TokenBufferMemory
from .mesh import (
    CrossProjectEntityResolver,
    DuplicationDetector,
    DuplicationMatch,
    GitRepoLoader,
    KnowledgeMesh,
    LocalMdLoader,
    MeshConfig,
    MeshDaemon,
    MeshHit,
    MeshIndexSummary,
    MeshPrivacyFilter,
    MeshQueryResult,
    MeshStatus,
)
from .observability import (
    AuditEntry,
    AuditLog,
    BudgetExceededError,
    BudgetGuard,
    BudgetLimit,
    CircuitState,
    CostRecord,
    CostTracker,
    DistributedTracer,
    OTelExporter,
    PrometheusMetrics,
    Span,
    TraceSpan,
    TracingMiddleware,
    TracingUI,
)
from .observability.tracer import TokenTracer
from .parsers.json_parser import JSONParser
from .parsers.list_parser import ListParser
from .parsers.pydantic_parser import PydanticParser
from .plugins import PluginRegistry
from .prompts.hub import PromptHub
from .prompts.template import ChatPromptTemplate, FewShotPromptTemplate, PromptTemplate
from .provenance import GroundedSignal, SignalSource
from .rag.facade import RAG
from .rag.pipeline import RAGConfig, RAGPipeline
from .rag.self_healing import SelfHealingRAG
from .retrieval.adaptive import AdaptiveRAGRetriever
from .retrieval.base import VectorStore
from .retrieval.cohere_reranker import CohereReranker
from .retrieval.contextual import ContextualRetriever
from .retrieval.contextual_compression import ContextualCompressionRetriever
from .retrieval.crag import CRAGRetriever
from .retrieval.cross_encoder import CrossEncoderReranker
from .retrieval.ensemble import EnsembleRetriever
from .retrieval.flare import FLARERetriever
from .retrieval.graphrag import GraphRAGRetriever, KnowledgeGraph
from .retrieval.hybrid_search import HybridSearchRetriever
from .retrieval.hyde import HyDERetriever
from .retrieval.jina_reranker import JinaReranker
from .retrieval.mixedbread_reranker import MixedbreadReranker
from .retrieval.mongodb_atlas import MongoDBAtlasVectorStore
from .retrieval.multi_step import MultiStepRetriever
from .retrieval.okf_graph import okf_to_world_model
from .retrieval.parent_document import ParentDocumentRetriever
from .retrieval.property_graph import (
    ExtractedEntity,
    ExtractedRelationship,
    GraphVectorStore,
    KnowledgeGraphExtraction,
    KnowledgeGraphExtractor,
    Neo4jPropertyGraphBackend,
    NetworkXPropertyGraphBackend,
    PropertyGraphEdge,
    PropertyGraphNode,
)
from .retrieval.query_decomposition import QueryDecompositionRetriever
from .retrieval.rag_fusion import RAGFusionRetriever
from .retrieval.retriever import Retriever
from .retrieval.self_query import SelfQueryRetriever
from .retrieval.self_rag import SelfRAGRetriever
from .retrieval.sentence_window import SentenceWindowRetriever
from .retrieval.step_back import StepBackRetriever
from .retrieval.vectorstore import InMemoryVectorStore
from .retrieval.voyage_reranker import VoyageReranker
from .retrieval.world_model import (
    CausalLinker,
    EntityMention,
    EntityResolver,
    EventMention,
    ExtractionPolicy,
    ExtractionResult,
    GraphQueryResult,
    HeuristicWorldModelExtractor,
    HybridWorldModelRetriever,
    InMemoryWorldGraphBackend,
    KuzuWorldGraphBackend,
    LLMWorldModelExtractor,
    Neo4jWorldGraphBackend,
    RelationMention,
    WorldModelEdge,
    WorldModelNode,
    WorldModelQueryResult,
    WorldModelRAG,
)
from .structured_output import (
    IncrementalJSONBuffer,
    StructuredOutput,
    StructuredOutputAttempt,
    StructuredOutputError,
    StructuredOutputResult,
    StructuredOutputRetryStrategy,
    StructuredOutputStreamEvent,
    StructuredOutputValidationError,
    build_corrective_prompt,
    structured_output,
)
from .text_splitters import (
    BaseSplitter,
    CharacterTextSplitter,
    CodeSplitter,
    HTMLTextSplitter,
    JSONSplitter,
    MarkdownTextSplitter,
    RecursiveCharacterTextSplitter,
    SemanticSplitter,
    SentenceTextSplitter,
    SentenceWindowSplitter,
    TokenAwareSplitter,
)
from .timetravel import (
    AsOf,
    CommitInfo,
    DiffNarrativeGenerator,
    DriftCandidate,
    DriftDetector,
    EvolutionEntry,
    EvolutionIndex,
    GitBackend,
    TimeTravelAgent,
)
from .training import (
    ANTHROPIC_TRAINING_RATE_PER_M_TOKENS,
    OPENAI_TRAINING_RATE_PER_M_TOKENS,
    PROVIDER_PRICING,
    ABTestMetrics,
    ABTestResult,
    ABTestRouter,
    AnthropicFineTuneProvider,
    AutoRolloutManager,
    BaseFineTuneProvider,
    ContinuousTrainer,
    CostBenefitAnalyzer,
    CostBenefitReport,
    FeedbackBackend,
    FeedbackCollector,
    FeedbackSample,
    FineTuneJob,
    InferenceProfile,
    InMemoryFeedbackBackend,
    OpenAIFineTuneProvider,
    PreferencePair,
    RolloutPolicy,
    RolloutState,
    TrainingDataGenerator,
    TrainingExample,
)
from .twin import (
    ApprovalRequiredError,
    AutoSendForbiddenError,
    DelegationLevel,
    DelegationPolicy,
    DigitalTwinAgent,
    DraftResult,
    LearnedPatterns,
    StyleProfile,
    VoiceMatcher,
    VoiceMatchResult,
)
from .ump import (
    AiderAdapter,
    BaseUMPAdapter,
    ClaudeAdapter,
    ContinueAdapter,
    CursorAdapter,
    UMPDocument,
    UMPFrontmatter,
    UMPProvenance,
    UMPReader,
    UMPScope,
    UMPType,
    UMPValidator,
    UMPVisibility,
    UMPWriter,
    ValidationError,
    ValidationResult,
    auto_detect_and_convert,
)

__version__ = "2.0.1"
__all__ = [
    # Facade
    "RAG",
    "SelfHealingRAG",
    # Pipeline
    "RAGPipeline",
    "RAGConfig",
    # LLM
    "AsyncLRUCache",
    "DynamoDBCacheBackend",
    "MemcachedCacheBackend",
    "BaseLLM",
    "LLMConfig",
    "CostQualityRouter",
    "CostRouter",
    "CostRouterConfig",
    "RouterModelSpec",
    "QUALITY_TABLE",
    "EdgeFallbackBlockedError",
    "EdgeRouteMetadata",
    "EdgeRuntime",
    "FallbackPolicy",
    "FallbackChain",
    "FallbackChainConfig",
    "BaseReasoningProvider",
    "AlephAlphaLLM",
    "AzureOpenAILLM",
    "CerebrasLLM",
    "CloudflareLLM",
    "DeepSeekLLM",
    "FireworksLLM",
    "GroqLLM",
    "GPT4AllLLM",
    "HuggingFaceLLM",
    "MinimaxLLM",
    "MoonshotLLM",
    "NovitaLLM",
    "OpenRouterLLM",
    "PerplexityLLM",
    "ReasoningLLM",
    "ReasoningResponse",
    "ReasoningStreamChunk",
    "SambaNovaLLM",
    "TogetherLLM",
    "VertexAILLM",
    "XaiLLM",
    "WriterLLM",
    "ZhipuLLM",
    "LMStudioLLM",
    "MLXLLM",
    "VLLMLLM",
    # Embeddings
    "SynapsekitEmbeddings",
    "ONNXEmbeddings",
    "OpenAIEmbeddings",
    "CohereEmbeddings",
    "VoyageEmbeddings",
    "JinaEmbeddings",
    "GeminiEmbeddings",
    "MistralEmbeddings",
    "NomicEmbeddings",
    "MixedbreadEmbeddings",
    "HuggingFaceEmbeddings",
    # Vector stores
    "VectorStore",
    "InMemoryVectorStore",
    "GraphVectorStore",
    "GroundedSignal",
    "SignalSource",
    "ChromaVectorStore",
    "FAISSVectorStore",
    "LanceDBVectorStore",
    "MilvusVectorStore",
    "MongoDBAtlasVectorStore",
    "PGVectorStore",
    "QdrantVectorStore",
    "PineconeVectorStore",
    "WeaviateVectorStore",
    "SQLiteVecStore",
    # Retrieval
    "Retriever",
    "AdaptiveRAGRetriever",
    "CohereReranker",
    "HybridSearchRetriever",
    "JinaReranker",
    "MixedbreadReranker",
    "MultiStepRetriever",
    "RAGFusionRetriever",
    "ContextualRetriever",
    "ContextualCompressionRetriever",
    "CRAGRetriever",
    "CrossEncoderReranker",
    "EnsembleRetriever",
    "FLARERetriever",
    "HyDERetriever",
    "ParentDocumentRetriever",
    "QueryDecompositionRetriever",
    "SelfQueryRetriever",
    "SelfRAGRetriever",
    "SentenceWindowRetriever",
    "VoyageReranker",
    "GraphRAGRetriever",
    "KnowledgeGraph",
    "KnowledgeGraphExtraction",
    "KnowledgeGraphExtractor",
    "NetworkXPropertyGraphBackend",
    "Neo4jPropertyGraphBackend",
    "PropertyGraphNode",
    "PropertyGraphEdge",
    "ExtractedEntity",
    "ExtractedRelationship",
    "StepBackRetriever",
    "WorldModelRAG",
    "okf_to_world_model",
    "ExtractionPolicy",
    "EntityMention",
    "RelationMention",
    "EventMention",
    "ExtractionResult",
    "EntityResolver",
    "CausalLinker",
    "GraphQueryResult",
    "HeuristicWorldModelExtractor",
    "HybridWorldModelRetriever",
    "InMemoryWorldGraphBackend",
    "KuzuWorldGraphBackend",
    "LLMWorldModelExtractor",
    "Neo4jWorldGraphBackend",
    "WorldModelEdge",
    "WorldModelNode",
    "WorldModelQueryResult",
    "KnowledgeMesh",
    "MeshConfig",
    "MeshDaemon",
    "MeshHit",
    "MeshIndexSummary",
    "MeshPrivacyFilter",
    "MeshQueryResult",
    "MeshStatus",
    "CrossProjectEntityResolver",
    "DuplicationDetector",
    "DuplicationMatch",
    # Digital Twin Agent
    "DigitalTwinAgent",
    "StyleProfile",
    "LearnedPatterns",
    "VoiceMatcher",
    "VoiceMatchResult",
    "DelegationPolicy",
    "DelegationLevel",
    "DraftResult",
    "ApprovalRequiredError",
    "AutoSendForbiddenError",
    # Universal Memory Protocol (UMP)
    "UMPDocument",
    "UMPFrontmatter",
    "UMPProvenance",
    "UMPType",
    "UMPScope",
    "UMPVisibility",
    "UMPReader",
    "UMPWriter",
    "UMPValidator",
    "ValidationError",
    "ValidationResult",
    "BaseUMPAdapter",
    "ClaudeAdapter",
    "CursorAdapter",
    "AiderAdapter",
    "ContinueAdapter",
    "auto_detect_and_convert",
    # Time Travel Codebase
    "TimeTravelAgent",
    "AsOf",
    "CommitInfo",
    "DiffNarrativeGenerator",
    "DriftCandidate",
    "DriftDetector",
    "EvolutionEntry",
    "EvolutionIndex",
    "GitBackend",
    # Cost intelligence
    "CostTracker",
    "CostRecord",
    "BudgetGuard",
    "BudgetLimit",
    "BudgetExceededError",
    "CircuitState",
    # Memory / observability
    "PersistentAgentMemory",
    "GraphAgentMemory",
    "GraphMemoryBackend",
    "BufferMemory",
    "ConversationMemory",
    "EntityMemory",
    "HybridMemory",
    "RedisConversationMemory",
    "SmartContextManager",
    "SQLiteConversationMemory",
    "SummaryBufferMemory",
    "TokenBufferMemory",
    "LivingMemory",
    "MemoryPatch",
    "OccurrenceRecord",
    "MemoryFileCategory",
    "PatchStatus",
    "FileDiffEngine",
    "DiffConflictError",
    "PatchStore",
    "OccurrenceTracker",
    "MemoryPIIFilter",
    "PIIFilterResult",
    "MemoryFileRouter",
    "TokenTracer",
    "PrometheusMetrics",
    # Loaders
    "Document",
    "TextLoader",
    "ArXivLoader",
    "AzureBlobLoader",
    "BigQueryLoader",
    "StringLoader",
    "PDFLoader",
    "HTMLLoader",
    "CSVLoader",
    "TSVLoader",
    "ConfigLoader",
    "JSONLoader",
    "DirectoryLoader",
    "DropboxLoader",
    "EPUBLoader",
    "ElasticsearchLoader",
    "ConfluenceLoader",
    "DocxLoader",
    "EmailLoader",
    "GCSLoader",
    "GitHubLoader",
    "GitLoader",
    "GitRepoLoader",
    "GoogleSheetsLoader",
    "HubSpotLoader",
    "JiraLoader",
    "LaTeXLoader",
    "MarkdownLoader",
    "LocalMdLoader",
    "ObsidianLoader",
    "OKFLoader",
    "OpenKnowledgeFormatLoader",
    "MongoDBLoader",
    "DynamoDBLoader",
    "OneDriveLoader",
    "SQLLoader",
    "SupabaseLoader",
    "TeamsLoader",
    "WebLoader",
    "RSSLoader",
    "RTFLoader",
    "RedisLoader",
    "S3Loader",
    "SalesforceLoader",
    "SitemapLoader",
    "SnowflakeLoader",
    "WikipediaLoader",
    "ExcelLoader",
    "PowerPointLoader",
    "ParquetLoader",
    "PubMedLoader",
    "SitemapLoader",
    "YouTubeLoader",
    # Parsers
    "JSONParser",
    "PydanticParser",
    "ListParser",
    # Prompts
    "PromptHub",
    "PromptTemplate",
    "ChatPromptTemplate",
    "FewShotPromptTemplate",
    # Agents
    "BaseTool",
    "ToolResult",
    "ToolRegistry",
    "AgentMetadata",
    "AgentRegistry",
    "InMemoryAgentRegistry",
    "RedisAgentRegistry",
    "Reputation",
    "RedisReputation",
    "ReputationSnapshot",
    "AgentClient",
    "LocalAgentClient",
    "AgentFederation",
    "AgentRoutingStrategy",
    "RoutingStrategy",
    "AgentMemory",
    "AgentScratchpad",
    "AgentStep",
    "AgentConfigPatch",
    "AgentConfigSnapshot",
    "AgentEvolutionAuditLog",
    "AnthropicComputerUseProvider",
    "BrowserScreenProvider",
    "ComputerAction",
    "ComputerActionType",
    "ComputerObservation",
    "ComputerStep",
    "ComputerUseAgent",
    "ComputerUseProvider",
    "ComputerUseResult",
    "LocalScreenProvider",
    "OpenAIComputerUseProvider",
    "OpenSourceComputerUseProvider",
    "SafetyPolicy",
    "ScreenProvider",
    "SessionRecorder",
    "VNCScreenProvider",
    "requires_human_confirmation",
    "ReActAgent",
    "ReasoningAgent",
    "ReasoningAgentConfig",
    "ReasoningDecision",
    "FunctionCallingAgent",
    "SelfImprovingAgent",
    "MetaAnalyzer",
    "EvolutionCycleResult",
    "AgentExecutor",
    "AgentConfig",
    "CronTrigger",
    "TriggerResult",
    "AgentBidder",
    "AgentSwarm",
    "AuctionResult",
    "AuctionType",
    "Bid",
    "BidStrategy",
    "CoalitionFormer",
    "MarketPolicy",
    "SwarmResult",
    "SimpleAgent",
    "VoiceAgent",
    "VoiceResult",
    "agent",
    # Tool decorator
    "tool",
    # Multi-agent
    "Crew",
    "CrewAgent",
    "CrewResult",
    "Handoff",
    "HandoffChain",
    "HandoffResult",
    "SupervisorAgent",
    "Task",
    "WorkerAgent",
    # MCP
    "MCPClient",
    "MCPServer",
    "MCPToolAdapter",
    # Built-in tools
    "ArxivSearchTool",
    "BingSearchTool",
    "BraveSearchTool",
    "BrowserTool",
    "CalculatorTool",
    "CodeInterpreterTool",
    "DateTimeTool",
    "DuckDuckGoSearchTool",
    "FileListTool",
    "FileReadTool",
    "FileWriteTool",
    "GraphQLTool",
    "HTTPRequestTool",
    "HumanInputTool",
    "ImageAnalysisTool",
    "ImageGenerationTool",
    "JiraTool",
    "JSONQueryTool",
    "LinearTool",
    "NewsTool",
    "PDFReaderTool",
    "PythonREPLTool",
    "RegexTool",
    "SentimentAnalysisTool",
    "ShellTool",
    "SlackTool",
    "SpeechToTextTool",
    "SQLQueryTool",
    "SQLSchemaInspectionTool",
    "SummarizationTool",
    "TavilySearchTool",
    "TextToSpeechTool",
    "TranslationTool",
    "TwilioTool",
    "EmailTool",
    "GitHubAPITool",
    "GoogleSearchTool",
    "PubMedSearchTool",
    "WebScraperTool",
    "WebSearchTool",
    "VectorSearchTool",
    "StripeTool",
    "WeatherTool",
    "WolframAlphaTool",
    "WikipediaTool",
    "YouTubeSearchTool",
    # Text splitters
    "BaseSplitter",
    "HTMLTextSplitter",
    "CharacterTextSplitter",
    "MarkdownTextSplitter",
    "RecursiveCharacterTextSplitter",
    "CodeSplitter",
    "JSONSplitter",
    "TokenAwareSplitter",
    "SemanticSplitter",
    "SentenceTextSplitter",
    "SentenceWindowSplitter",
    # Graph workflows
    "END",
    "GraphState",
    "GraphVisualizer",
    "get_mermaid_with_trace",
    "GraphConfigError",
    "GraphRuntimeError",
    "RecursionDepthError",
    "Node",
    "NodeFn",
    "agent_node",
    "approval_node",
    "dynamic_route_node",
    "llm_node",
    "rag_node",
    "subgraph_node",
    "GraphInterrupt",
    "InterruptState",
    "Edge",
    "ConditionalEdge",
    "ConditionFn",
    "EventHooks",
    "GraphEvent",
    "StateField",
    "StateGraph",
    "TypedState",
    "CompiledGraph",
    "ExecutionTrace",
    "TraceEntry",
    "fan_out_node",
    "sse_stream",
    "ws_stream",
    # Checkpointers
    "BaseCheckpointer",
    "InMemoryCheckpointer",
    "JSONFileCheckpointer",
    "PostgresCheckpointer",
    "RedisCheckpointer",
    "SQLiteCheckpointer",
    # Structured output
    "generate_structured",
    "IncrementalJSONBuffer",
    "StructuredOutput",
    "StructuredOutputAttempt",
    "StructuredOutputError",
    "StructuredOutputResult",
    "StructuredOutputRetryStrategy",
    "StructuredOutputStreamEvent",
    "StructuredOutputValidationError",
    "build_corrective_prompt",
    "structured_output",
    # Neuro-symbolic reasoning
    "BaseSymbolicBackend",
    "ConstraintExtractor",
    "ConstraintSet",
    "MiniZincBackend",
    "NeuroSymbolicAgent",
    "NeuroSymbolicResult",
    "PrologBackend",
    "ProofTrace",
    "SymbolicBackend",
    "SympyBackend",
    "VerificationFailure",
    "VerifiedTool",
    "Z3Backend",
    "parse_constraint_response",
    "verified_tool",
    # Evaluation
    "EvalCaseMeta",
    "EvalSuite",
    "EvalSuiteResult",
    "EvalRegression",
    "EvalSnapshot",
    "EvaluationPipeline",
    "EvaluationResult",
    "FaithfulnessMetric",
    "GroundednessMetric",
    "MetricDelta",
    "MetricResult",
    "EmailAlertSink",
    "PagerDutyAlertSink",
    "PromptCandidate",
    "PromptOptimizer",
    "PromptVariantRunner",
    "RAGAlert",
    "RAGAlertSink",
    "RAGEvaluationResult",
    "RAGEvaluationThresholds",
    "RAGEvaluator",
    "RAGERemediationSuggestion",
    "SlackWebhookAlertSink",
    "RegressionReport",
    "RelevancyMetric",
    "eval_case",
    # Observability
    "AuditEntry",
    "AuditLog",
    "DistributedTracer",
    "OTelExporter",
    "Span",
    "TraceSpan",
    "TracingMiddleware",
    "TracingUI",
    # A2A Protocol
    "A2AClient",
    "A2AMessage",
    "A2AServer",
    "A2ATask",
    "AgentCard",
    "TaskState",
    # Guardrails
    "ContentFilter",
    "Guardrails",
    "GuardrailResult",
    "PIIDetector",
    "PIIRedactor",
    "RedactionResult",
    "TopicRestrictor",
    # Step events
    "ActionEvent",
    "ErrorEvent",
    "FinalAnswerEvent",
    "ObservationEvent",
    "StepEvent",
    "ThoughtEvent",
    "TokenEvent",
    # Multimodal
    "AudioContent",
    "ImageContent",
    "MultimodalMessage",
    "AudioLoader",
    "AirtableLoader",
    "VideoLoader",
    "ImageLoader",
    "YAMLLoader",
    "DiscordLoader",
    "XMLLoader",
    "GoogleDriveLoader",
    # Plugins
    "PluginRegistry",
    # Voice pipeline
    "VoicePipeline",
    # Voice base classes
    "BaseVAD",
    "BaseSTT",
    "BaseTTS",
    # VAD
    "EnergyVAD",
    "SileroVAD",
    # STT
    "LocalWhisperSTT",
    "OpenAIWhisperSTT",
    "DeepgramSTT",
    # TTS
    "OpenAITTS",
    "ElevenLabsTTS",
    "CartesiaTTS",
    "PiperTTS",
    # Voice types
    "AudioFrame",
    "TranscriptChunk",
    "PipelineEvent",
    "PipelineState",
    # API stability markers
    "deprecated",
    "experimental",
    "public_api",
    # Continuous fine-tuning pipeline
    "FeedbackSample",
    "TrainingExample",
    "PreferencePair",
    "FineTuneJob",
    "ABTestResult",
    "ABTestMetrics",
    "RolloutPolicy",
    "RolloutState",
    "CostBenefitReport",
    "FeedbackBackend",
    "FeedbackCollector",
    "InMemoryFeedbackBackend",
    "TrainingDataGenerator",
    "BaseFineTuneProvider",
    "OpenAIFineTuneProvider",
    "AnthropicFineTuneProvider",
    "ABTestRouter",
    "AutoRolloutManager",
    "CostBenefitAnalyzer",
    "InferenceProfile",
    "PROVIDER_PRICING",
    "OPENAI_TRAINING_RATE_PER_M_TOKENS",
    "ANTHROPIC_TRAINING_RATE_PER_M_TOKENS",
    "ContinuousTrainer",
    # Verifiable audit trail
    "AuditTracer",
    "AuditRecord",
    "EventKind",
    "Verdict",
    "Signature",
    "VerificationResult",
    "AuditVerificationError",
    "SigningPolicy",
    "MerkleHasher",
    "export_audit_bundle",
    "verify_audit_bundle",
    "ReplayEngine",
    "AuditSink",
    "FileAuditSink",
    "AuditMetrics",
    "VerifiableAgent",
    "AuditPIIRedactor",
    # Portable agent marketplace
    "AgentBundleFile",
    "AgentBundleVerification",
    "AgentManifest",
    "AgentMarketplaceError",
    "AgentSandbox",
    "FileAgentRegistry",
    "InstalledAgent",
    "InvalidAgentBundleError",
    "PublisherIdentity",
    "RankedRegistryEntry",
    "RegistryEntry",
    "SandboxRequiredError",
    "SignedAgentReview",
    "UntrustedPublisherError",
    "install_agent",
    "pack_agent",
    "unpack_agent",
    "verify_agent_bundle",
    # Hive Mode
    "AllowAllAuthorizer",
    "ContributionEnvelope",
    "ContributionPayload",
    "DifferentialPrivacy",
    "HIVE_SCHEMA_VERSION",
    "HiveAggregator",
    "HiveAggregatorError",
    "HiveClient",
    "HiveClientError",
    "HivePrivacyError",
    "HiveTransport",
    "HttpHiveTransport",
    "InProcessHiveTransport",
    "MinedPatterns",
    "PATTERN_VOCABULARY",
    "PatternMiner",
    "PatternObservation",
    "PrivacyBudgetLedger",
    "PrivacyConfig",
    "Pseudonymizer",
    "SQLiteHiveStore",
    "ShareScope",
    "Suggestion",
    "TransparencyReport",
    "create_hive_app",
    "stable_scope_id",
]

# Lazy imports for optional backends
_LAZY_IMPORTS = {
    # Vector stores
    "ChromaVectorStore": "retrieval.chroma",
    "FAISSVectorStore": "retrieval.faiss",
    "LanceDBVectorStore": "retrieval.lancedb",
    "MilvusVectorStore": "retrieval.milvus",
    "PGVectorStore": "retrieval.pgvector",
    "QdrantVectorStore": "retrieval.qdrant",
    "PineconeVectorStore": "retrieval.pinecone",
    "WeaviateVectorStore": "retrieval.weaviate",
    "SQLiteVecStore": "retrieval.sqlite_vec",
    "ONNXEmbeddings": "embeddings.onnx",
    "OpenAIEmbeddings": "embeddings.openai",
    "CohereEmbeddings": "embeddings.cohere",
    "VoyageEmbeddings": "embeddings.voyage",
    "JinaEmbeddings": "embeddings.jina",
    "GeminiEmbeddings": "embeddings.gemini",
    "MistralEmbeddings": "embeddings.mistral",
    "NomicEmbeddings": "embeddings.nomic",
    "MixedbreadEmbeddings": "embeddings.mixedbread",
    "HuggingFaceEmbeddings": "embeddings.huggingface",
    # LLM providers
    "AsyncLRUCache": "llm._cache",
    "DynamoDBCacheBackend": "llm._cache_dynamodb",
    "MemcachedCacheBackend": "llm._cache_memcached",
    "AzureOpenAILLM": "llm.azure_openai",
    "CerebrasLLM": "llm.cerebras",
    "VertexAILLM": "llm.vertex_ai",
    "DeepSeekLLM": "llm.deepseek",
    "FireworksLLM": "llm.fireworks",
    "GroqLLM": "llm.groq",
    "GPT4AllLLM": "llm.gpt4all",
    "HuggingFaceLLM": "llm.huggingface",
    "OpenRouterLLM": "llm.openrouter",
    "PerplexityLLM": "llm.perplexity",
    "SambaNovaLLM": "llm.sambanova",
    "TogetherLLM": "llm.together",
    "MinimaxLLM": "llm.minimax",
    "NovitaLLM": "llm.novita",
    "MoonshotLLM": "llm.moonshot",
    "AlephAlphaLLM": "llm.aleph_alpha",
    "XaiLLM": "llm.xai",
    "WriterLLM": "llm.writer",
    "ZhipuLLM": "llm.zhipu",
    "LMStudioLLM": "llm.lmstudio",
    "MLXLLM": "llm.mlx",
    "VLLMLLM": "llm.vllm",
    "CloudflareLLM": "llm.cloudflare",
    "BaseReasoningProvider": "llm.reasoning",
    "ReasoningLLM": "llm.reasoning",
    "ReasoningResponse": "llm.reasoning",
    "ReasoningStreamChunk": "llm.reasoning",
    # Neuro-symbolic reasoning
    "BaseSymbolicBackend": "symbolic",
    "ConstraintExtractor": "symbolic",
    "ConstraintSet": "symbolic",
    "MiniZincBackend": "symbolic",
    "NeuroSymbolicAgent": "symbolic",
    "NeuroSymbolicResult": "symbolic",
    "PrologBackend": "symbolic",
    "ProofTrace": "symbolic",
    "SymbolicBackend": "symbolic",
    "SympyBackend": "symbolic",
    "VerificationFailure": "symbolic",
    "VerifiedTool": "symbolic",
    "Z3Backend": "symbolic",
    "parse_constraint_response": "symbolic",
    "verified_tool": "symbolic",
    # Checkpointers
    "RedisCheckpointer": "graph.checkpointers.redis",
    "PostgresCheckpointer": "graph.checkpointers.postgres",
    # Loaders
    "AirtableLoader": "loaders.airtable",
    "AudioLoader": "loaders.audio",
    "VideoLoader": "loaders.video",
    "DocxLoader": "loaders.docx",
    "ExcelLoader": "loaders.excel",
    "PowerPointLoader": "loaders.pptx",
    "TeamsLoader": "loaders.teams",
    "YAMLLoader": "loaders.yaml_loader",
    "DiscordLoader": "loaders.discord",
    "XMLLoader": "loaders.xml_loader",
    "GoogleDriveLoader": "loaders.google_drive",
    "HubSpotLoader": "loaders.hubspot",
    "MongoDBLoader": "loaders.mongodb",
    "ObsidianLoader": "loaders.obsidian",
    "OKFLoader": "loaders.okf",
    "OpenKnowledgeFormatLoader": "loaders.okf",
    "OneDriveLoader": "loaders.onedrive",
    "AzureBlobLoader": "loaders.azure_blob",
    "BigQueryLoader": "loaders.bigquery",
    "S3Loader": "loaders.s3",
    "SalesforceLoader": "loaders.salesforce",
    "SnowflakeLoader": "loaders.snowflake",
    "SupabaseLoader": "loaders.supabase",
    "DropboxLoader": "loaders.dropbox",
    "ParquetLoader": "loaders.parquet",
    "PubMedLoader": "loaders.pubmed",
    "RedisLoader": "loaders.redis_loader",
    "ElasticsearchLoader": "loaders.elasticsearch",
    "SitemapLoader": "loaders.sitemap",
    "YouTubeLoader": "loaders.youtube",
    # Voice
    "VoicePipeline": "voice.pipeline",
    "AudioFrame": "voice.types",
    "TranscriptChunk": "voice.types",
    "PipelineEvent": "voice.types",
    "PipelineState": "voice.types",
    "BaseSTT": "voice.base",
    "BaseTTS": "voice.base",
    "BaseVAD": "voice.base",
    "EnergyVAD": "voice.vad",
    "SileroVAD": "voice.vad",
    "LocalWhisperSTT": "voice.stt",
    "OpenAIWhisperSTT": "voice.stt",
    "DeepgramSTT": "voice.stt",
    "OpenAITTS": "voice.tts",
    "ElevenLabsTTS": "voice.tts",
    "CartesiaTTS": "voice.tts",
    "PiperTTS": "voice.tts",
}


def __getattr__(name: str):
    if name in _LAZY_IMPORTS:
        import importlib

        mod = importlib.import_module(f".{_LAZY_IMPORTS[name]}", __name__)
        cls = getattr(mod, name)
        globals()[name] = cls
        return cls
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
